#!/usr/bin/env bash

# This hook is used to force the use of ssh instead of https to avoid
# restrictions on git operations that can be performed using a GitHub
# Actions token. Specifically, GitHub rejects pushes using the GitHub
# Actions if they modify the content of `.github/workflows`.

exec > >(tee -a /tmp/renovate/githooks-output.log) 2>&1

script_path="$(readlink -f -- "${BASH_SOURCE[0]}")"
args=("${@}")
echo "### ${script_path} ${args@Q} started $(date +%Y%m%dT%H%M%S) in $(pwd) ###" >&2

ps -fp $(ps --no-headers -o ppid -p "${$}"),"${$}" >&2

set -x -Eeuo pipefail

REPOSITORY="$(git remote get-url --push origin | sed -E -e 's,^(https?://|)[^/]*github.com[/:]([^/]+)/([^/]+)?$,\2/\3,' -e 's/.git$//g')"

git remote set-url origin "git@github.com:${REPOSITORY}.git"

