#!/usr/bin/env bash

# This script performs post-processing on any branches or pull requests
# that were updated by Renovate.

set -Eeuo pipefail

echo "Pushed branches:" >&2
# This file is populated by the `bin/renovate/githooks/pre-push` script.
cat /tmp/renovate/branches.ndjson >&2

# For some reason pre-push also runs for the default branch (i.e.
# `master`), so the content of `branches.ndjson` has to be filtered so
# that only branches that Renovate considers as it's own are extracted.
#
# This is done by comparing the branches in the `branches.ndjson` file
# with the branches in the `report.json` file, which is generated by
# Renovate.
#
# The `jq` script below creates an intersection of the unique branches
# in `branches.ndjson` and the unique branches in `report.json`, the end
# result is then a unique list of branches that Renovate has changed and
# that we want to postprocess.
jq \
    -c --slurpfile branches /tmp/renovate/branches.ndjson \
    '
    (.repositories | to_entries | map(.key as $repository | .value.branches[] | [$repository, .branchName]) | unique)
        as $report_branches |
    ([$branches.[] | [.repository, .branch]] | unique)
        as $_branches |
    (($_branches - ($_branches - $report_branches)) | [.[] | {"repository": .[0], "branch": .[1]}]) |
    .[]' \
    /tmp/renovate/report.json >/tmp/renovate/branches-unique.ndjson

echo "Postprocessing these branches:" >&2
cat /tmp/renovate/branches-unique.ndjson >&2

errors=false

while IFS= read -r line; do
    echo "Postprocessing branch: ${line}" >&2
    REPOSITORY="$(jq -er '.repository' <<<"${line}")"
    BRANCH="$(jq -er '.branch' <<<"${line}")"
    export REPOSITORY BRANCH
    declare -p REPOSITORY BRANCH >&2

    PR_NUMBER="$(jq -er '[.repositories[env.REPOSITORY].branches[] | select(.branchName == env.BRANCH)][0] | .prNo' /tmp/renovate/report.json)"
    declare -p PR_NUMBER

    if [ "${RENOVATE_AUTO_APPROVE}" == "true" ]
    then
        echo "Auto-approving PR for branch: ${BRANCH} ${PR_NUMBER}" >&2
        curl --silent --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${RENOVATE_GITHUB_ACTIONS_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${REPOSITORY}/pulls/${PR_NUMBER}/reviews" \
            -d '{"body":"Auto-approve by workflow.","event":"APPROVE"}'
    else
        echo "Not auto-approving PR for branch: ${BRANCH} ${PR_NUMBER} as RENOVATE_AUTO_APPROVE is ${RENOVATE_AUTO_APPROVE@Q} and not 'true'" >&2
    fi

done < <(sort <"/tmp/renovate/branches-unique.ndjson" | uniq)

if [ "${errors}" = true ]; then
    exit 1
fi
