name: renovate auto-approve
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'github-actions[bot]' }}
    steps:
      - name: Approve a PR
        run: |
          gh pr review --approve "${PULL_REQUEST_URL}" --body "Auto-approved by workflow."
        env:
          PULL_REQUEST_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
