# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# This workflow extracts the environment variables needed to run
# Renovate manually. It remains active for {lifetime} seconds so the
# GitHub Action token remains valid, but the task that invokes it kills
# it as soon as it's done with the tokens.
name: renovate-env

on:
  workflow_dispatch:
    inputs:
      lifetime:
        description: 'How long should the tokens be valid for'
        type: number
        default: 120
      gpg_public_key:
        required: true
        description: 'The public key to use for GPG encryption'
        type: string

concurrency:
  group: >
    ${{ github.repository }}-
    ${{ github.workflow }}-
  cancel-in-progress: true

permissions:
#   contents: write
  pull-requests: write
#   issues: write
#   actions: read
#   security-events: read
#   statuses: write
#   checks: read

jobs:
  renovate-env:
    runs-on: ubuntu-latest
    steps:
      - name: Export Renovate Secrets
        run: |
          set -Eeuo pipefail

          printenv GPG_PUBLIC_KEY > /var/tmp/gpg.pub

          {
            echo "RENOVATE_TOKEN=${RENOVATE_TOKEN@Q}"
            echo "RENOVATE_GITHUB_ACTIONS_TOKEN=${RENOVATE_GITHUB_ACTIONS_TOKEN@Q}"
          } | gpg --encrypt --armor --recipient-file /var/tmp/gpg.pub > /var/tmp/renovate-env.asc
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GPG_PUBLIC_KEY: ${{ github.event.inputs.gpg_public_key }}
      - uses: actions/upload-artifact@v4
        with:
          name: renovate-env
          path: /var/tmp/renovate-env.asc
          retention-days: 1
      - run: |
          set -Eeuo pipefail
          sleep ${{ github.event.inputs.lifetime }}
