name: ssh-debug

on:
  workflow_dispatch:
    inputs:
      ssh_public_key:
        description: 'The public key to add to authorized_keys'
        type: string
        default: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEdhlqu53pND3KnDK9J+xwTfQaCBSbD9zrE8hImvX3C0OKJuTCn4SWCXBKRz9nmzJ7SxbhYd1+sJltV0nP2+rcApGV+mIMhgB2ntrvTgUNQpx70PPAxbblITzVIeldSq2W7x07fgVB6eMQEKYwhrDv3mjEJtqJz+HkFQMmh7jCWCaj5JL3BZNJ2kBNM5WsWkB0U1qFYF1JG3cdlAJpeqYzAWzrH0Of5sXn3AzvahR70T7m8x4WeSe/2G9lPdTa/p0kRFFHx9bYzwfyI9J6eXl0LpZFoPqwd+TeK6lW57MCHZED7pb3p/EwATULJjlEx9NSf7XZa8aa/jCP8UwTjjc1K+kne9pcI2bo+kTtSVPpnmIgsHZY7O4sY6c+ScXrtsPLzMhHeDFbUuxYhumZjuWf4SZ7zSkpydFFvj5waAgR3RvXTTuWxCAhjaHPhygR0TLmb9KrwSOXZP1REDA2Vm7QZK/0G4GxasUocnqzZXAOlaQK1JUGKqzpnqefuyPjH7+W2e968GODfzFJk2EQxf9cRRZgmsbXEDctoJLvNSNpZzTQzQ1IZQE1CTtwaZv6Yjaii04bgS56CWXDqYOpxU3gw0xZyC6zf92ZlsIStEj2z3tveXKK/x1proQEXQQZHBqU2jEse7LOJGKHGA1YG7+hnqDRH+xMfOkjBhZb4Oc6Hw== tb0@tb0-pw090cxn/20250331-000

concurrency:
  group: >
    ${{ github.repository }}-
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && format( '{0}-{1}', github.run_id, github.sha ) || '' }}
  cancel-in-progress: true

permissions: write-all

jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Start sshd
        run: |
          set -xEeuo pipefail

          declare -p > ~/runner.env
          mkdir -vp ~/.ssh/
          printenv NGROK_SSH_PRIVATE_KEY > ~/.ssh/id_rsa
          echo >> ~/.ssh/id_rsa
          sudo chmod go-rwx ~/

          echo "Installing and starting the SSH server"
          sudo apt-get install -y openssh-server
          sudo mkdir -vp /run/sshd
          sudo /usr/sbin/sshd -D &

          echo "Adding SSH public key to authorized_keys"
          mkdir -vp ~/.ssh/
          echo '${{github.event.inputs.ssh_public_key}}' >> ~/.ssh/authorized_keys
          chmod -vR go-rwx ~/.ssh/ || :
          cat ~/.ssh/authorized_keys

          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o ControlPath=none -R 0:localhost:22 v2@connect.ngrok-agent.com tcp
        env:
          NGROK_SSH_PRIVATE_KEY: ${{ secrets.NGROK_SSH_PRIVATE_KEY }}
