name: ssh-debug

on:
  workflow_dispatch:
    inputs:
      ssh_public_key:
        description: 'The public key to add to authorized_keys'
        type: string
        required: true

concurrency:
  group: >
    ${{ github.repository }}-
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && format( '{0}-{1}', github.run_id, github.sha ) || '' }}
  cancel-in-progress: true

permissions: write-all

jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Start sshd
        run: |
          set -xEeuo pipefail

          uname -a >&2
          id >&2

          declare -p > ~/runner.env
          mkdir -vp ~/.ssh/
          printenv NGROK_SSH_PRIVATE_KEY > ~/.ssh/id_rsa
          echo >> ~/.ssh/id_rsa
          sudo chmod go-rwx ~/

          echo "Starting the SSH server"
          sudo mkdir -vp /run/sshd
          sudo /usr/sbin/sshd -D &

          echo "Adding SSH public key to authorized_keys"
          mkdir -vp ~/.ssh/
          printenv USER_SSH_PUBLIC_KEY >> ~/.ssh/authorized_keys
          chmod -vR go-rwx ~/.ssh/ || :
          cat ~/.ssh/authorized_keys

          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o ControlPath=none -R 0:localhost:22 v2@connect.ngrok-agent.com tcp
        env:
          NGROK_SSH_PRIVATE_KEY: ${{ secrets.NGROK_SSH_PRIVATE_KEY }}
          USER_SSH_PUBLIC_KEY: ${{ github.event.inputs.ssh_public_key }}
