name: Validate

on:
  # push: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

concurrency:
  group: >
    ${{ github.repository }}-
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref) && format( '{0}-{1}', github.run_id, github.sha ) || '' }}
  cancel-in-progress: true

env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache/xdg

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      # Need to add repo here first:
      # https://github.com/users/aucampia/packages/container/cookiecutter-python/settings
      - name: Log in to the Container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache xdg
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: xdg-${{ github.job }}-v1-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            xdg-${{ github.job }}-v1
            xdg-${{ github.job }}
      - name: Run validation
        run: |
          set -x -Eeuo pipefail
          # printenv GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx create --name main --driver=docker-container --bootstrap --use
          docker compose run --build --rm devtools task configure validate:static
          sudo chown -R "$(id -u):$(id -g)" .
        env:
          DOCKER_BUILDKIT_CACHE_TO: "type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max"
          DOCKER_BUILDKIT_CACHE_FROM: "type=registry,ref=ghcr.io/${{ github.repository }}:cache"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
